server:
  port: 3000
  basePath: ''
application:
  domain: juice-sh.op
  name: 'CSTAD Cafe'
  logo: coffee.png
  favicon: favicon_js.ico
  theme: bluegrey-lightgreen # Options: bluegrey-lightgreen blue-lightblue deeppurple-amber indigo-pink pink-bluegrey purple-green deeporange-indigo
  showVersionNumber: true
  showGitHubLinks: true
  localBackupEnabled: true
  numberOfRandomFakeUsers: 0
  altcoinName: Juicycoin
  privacyContactEmail: donotreply@owasp-juice.shop
  customMetricsPrefix: juiceshop
  chatBot:
    name: 'Juicy'
    greeting: "Nice to meet you <customer-name>, I'm <bot-name>"
    trainingData: 'botDefaultTrainingData.json'
    defaultResponse: "Sorry I couldn't understand what you were trying to say"
    avatar: 'JuicyChatBot.png'
  social:
    twitterUrl: 'https://twitter.com/owasp_juiceshop'
    facebookUrl: 'https://www.facebook.com/owasp.juiceshop'
    slackUrl: 'https://owasp.org/slack/invite'
    redditUrl: 'https://www.reddit.com/r/owasp_juiceshop'
    pressKitUrl: 'https://github.com/OWASP/owasp-swag/tree/master/projects/juice-shop'
    nftUrl: 'https://opensea.io/collection/juice-shop'
    questionnaireUrl: ~
  recyclePage:
    topProductImage: fruit_press.jpg
    bottomProductImage: apple_pressings.jpg
  welcomeBanner:
    showOnFirstStart: true
    title: 'Welcome to OWASP Juice Shop!'
    message: "<p>Being a web application with a vast number of intended security vulnerabilities, the <strong>OWASP Juice Shop</strong> is supposed to be the opposite of a best practice or template application for web developers: It is an awareness, training, demonstration and exercise tool for security risks in modern web applications. The <strong>OWASP Juice Shop</strong> is an open-source project hosted by the non-profit <a href='https://owasp.org' target='_blank'>Open Web Application Security Project (OWASP)</a> and is developed and maintained by volunteers. Check out the link below for more information and documentation on the project.</p><h1><a href='https://owasp-juice.shop' target='_blank'>https://owasp-juice.shop</a></h1>"
  cookieConsent:
    message: 'This website uses fruit cookies to ensure you get the juiciest tracking experience.'
    dismissText: 'Me want it!'
    linkText: 'But me wait!'
    linkUrl: 'https://www.youtube.com/watch?v=9PnbKL3wuH4'
  securityTxt:
    contact: 'mailto:donotreply@owasp-juice.shop'
    encryption: 'https://keybase.io/bkimminich/pgp_keys.asc?fingerprint=19c01cb7157e4645e9e2c863062a85a8cbfbdcda'
    acknowledgements: '/#/score-board'
    hiring: '/#/jobs'
  promotion:
    video: owasp_promo.mp4
    subtitles: owasp_promo.vtt
  easterEggPlanet:
    name: Orangeuze
    overlayMap: orangemap2k.jpg
  googleOauth:
    clientId: '1005568560502-6hm16lef8oh46hr2d98vf2ohlnj4nfhq.apps.googleusercontent.com'
    authorizedRedirects:
      - { uri: 'https://demo.owasp-juice.shop' }
      - { uri: 'https://juice-shop.herokuapp.com' }
      - { uri: 'https://preview.owasp-juice.shop' }
      - { uri: 'https://juice-shop-staging.herokuapp.com' }
      - { uri: 'https://juice-shop.wtf' }
      - { uri: 'http://localhost:3000', proxy: 'https://local3000.owasp-juice.shop' }
      - { uri: 'http://127.0.0.1:3000', proxy: 'https://local3000.owasp-juice.shop' }
      - { uri: 'http://localhost:4200', proxy: 'https://local4200.owasp-juice.shop' }
      - { uri: 'http://127.0.0.1:4200', proxy: 'https://local4200.owasp-juice.shop' }
      - { uri: 'http://192.168.99.100:3000', proxy: 'https://localmac.owasp-juice.shop' }
      - { uri: 'http://192.168.99.100:4200', proxy: 'https://localmac.owasp-juice.shop' }
      - { uri: 'http://penguin.termina.linux.test:3000', proxy: 'https://localchromeos.owasp-juice.shop' }
      - { uri: 'http://penguin.termina.linux.test:4200', proxy: 'https://localchromeos.owasp-juice.shop' }
challenges:
  showSolvedNotifications: true
  showHints: true
  showMitigations: true
  codingChallengesEnabled: solved # Options: never  solved  always
  restrictToTutorialsFirst: false
  overwriteUrlForProductTamperingChallenge: 'https://owasp.slack.com'
  xssBonusPayload: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/771984076&color=%23ff5500&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>'
  safetyOverride: false
  showFeedbackButtons: true
hackingInstructor:
  isEnabled: true
  avatarImage: JuicyBot.png
  hintPlaybackSpeed: normal # Options: faster fast normal slow slower
products:
  -
    name: 'Milk Tea'
    price: 1.99
    deluxePrice: 0.99
    limitPerUser: 5
    description: 'Made from black tea and milk. Contains caffeine.'
    image: 1.png
    reviews:
      - { text: 'One of my favorites!', author: admin }
  -
    name: 'Caramel Frappuccino'
    description: 'Made from coffee, milk and caramel. Contains caffeine.'
    price: 2.99
    deluxePrice: 2.49
    image: 2.png
    reviews:
      - { text: 'y0ur f1r3wall needs m0r3 musc13', author: uvogin }
  -
    name: 'Caramel Macchiato'
    description: 'Made from coffee, milk and caramel. Contains caffeine.'
    price: 1.99
    image: 3.jpg
    reviews:
      - { text: 'I bought it, would buy again. 5/7', author: admin }
  -
    name: 'Iced Caffe latte'
    description: 'Made from coffee and milk. Contains caffeine.'
    price: 0.99
    image: 4.jpg
  -
    name: 'Mocha Frappuccino'
    description: 'Made from coffee, milk and chocolate. Contains caffeine.'
    price: 2.99
    deluxePrice: 1.99
    limitPerUser: 5
    image: 5.jpg
  -
    name: 'Iced Green Tea Latte'
    description: 'Made from green tea and milk. Contains bubble tea pearls.'
    price: 1.99
    image: 10.png
    reviews:
      - { text: 'Fry liked it too.', author: bender }
  -
    name: 'Blueberry Soda'
    description: 'Made from blueberries and soda.'
    price: 22.49
    limitPerUser: 5
    image: 11.png
  
  -
    name: 'black soda'
    description: 'Made from blackberries and soda.'
    price: 2.01
    image: setha.png
    urlForProductTamperingChallenge: 'https://www.owasp.org/index.php/O-Saft'
  -
    name: 'Brown Sugar'
    description: 'Made from brown sugar.'
    price: 2.99
    image: 14.png
    useForChristmasSpecialChallenge: true
  -
    name: 'Hot Latte'
    description: 'Contains a magical collection of the rarest fruits gathered from all around the world, like Cherymoya Annona cherimola, Jabuticaba Myrciaria cauliflora, Bael Aegle marmelos... and others, at an unbelievable price! <br/><span style="color:red;">This item has been made unavailable because of lack of safety standards.</span>'
    price: 16.99
    image: 15.png
    keywordsForPastebinDataLeakChallenge:
      - hueteroneel
      - eurogium edule
  -
    name: 'Hot Capuccino'
    description: 'Die-cut sticker with the official 2015/2016 logo. By now this is a rare collectors item. <em>Out of stock!</em>'
    price: 1.99
    image: 16.png
    deletedDate: '2017-04-28'
  -
    name: 'Chocolate Frappe'
    description: 'Made from coffee, milk and chocolate. Contains caffeine.'
    price: 4.99
    image: 21.png
  -
    name: 'IT Coffee (16pcs)'
    description: 'best product for this shop , very good taste and very good price'
    price: 1.99
    image: 22.png
  -
    name: 'Iced Americano'
    description: 'Made from coffee and water. Contains caffeine.'
    price: 1.99
    image: 33.png
  -
    name: 'Iced Matcha Latte'
    description: 'Made from matcha and milk. Contains bubble tea pearls.'
    price: 4.99
    image: 31.png
  -
    name: 'Hot Matcha Latte'
    description: 'Made from matcha and milk. Contains bubble tea pearls. hot hot spicy spicy'
    price: 1.99
    image: 26.png
    reviews:
      - { text: 'I straight-up gots nuff props fo''these tattoos!', author: rapper }
  -
    name: 'khmer Cafe'
    description: 'Best tranditional coffee in cambodia'
    price: 0.99
    image: 106.png
  -
    name: 'Coconut Coffee'
    description: 'Made from coffee and coconut milk. Contains caffeine.'
    price: 1.99
    image: 110.png
  -
    name: 'Coconut Khmer'
    description: 'Coconut Khmer product jai dep jai dep'
    price: 2.92
    quantity: 5
    limitPerUser: 5
    image: 114.png
    reviews:
      - { text: 'This thang would look phat on Bobby''s jacked fur coat!', author: rapper }
      - { text: 'Looks so much better on my uniform than the boring Starfleet symbol.', author: jim }
  -
    name: 'Coconut Khmer Frappe'
    description: 'Coconut from Kompong Cham'
    price: 1.99
    image: 115.png
  -
    name: 'Green Smoothie'
    description: 'Looks poisonous but is actually very good for your health! Made from green cabbage, spinach, kiwi and grass.'
    price: 1.99
    image: 134.png
    reviews:
      - { text: 'Fresh out of a replicator.', author: jim }
  -
    name: 'Watermelon Smoothie'
    description: 'Juice of the <em>Cydonia oblonga</em> fruit. Not exactly sweet but rich in Vitamin C.'
    price: 2.99
    image: 153.png
  -
    name: 'Strawberry Smoothie'
    description: 'Finest pressings of strawberry. Allergy disclaimer: Might contain traces of worms. Can be <a href="/#recycle">sent back to us</a> for recycling.'
    price: 1.89
    limitPerUser: 5
    image: 150.png
  -
    name: 'Blueberry Smoothie'
    description: 'Fruits go in. Juice comes out. Pomace you can send back to us for recycling purposes.'
    price: 2.99
    image: 135.png
  -
    name: 'Passion Fruit Smoothie'
    description: 'This rare item was designed and handcrafted in Sweden. This is why it is so incredibly expensive despite its complete lack of purpose.'
    price: 2.99
    image: 140.png # Exif metadata contains "OpenSCAD" as subtle hint...
    fileForRetrieveBlueprintChallenge: JuiceShop.stl # ...to blueprint file type
    exifForBlueprintChallenge:
      - OpenSCAD
  -
    name: 'Passion Soda'
    description: 'Very delicious and very expensive.'
    price: 8.74
    quantity: 0
    image: 141.png
    deletedDate: '2020-12-24'
  -
    name: 'Avocado smoothie'
    description: 'Sweet and tasty!'
    price: 2.03
    image: 133.png
    deletedDate: '2017-07-01'
  -
    name: 'Strawberry Juice (500ml)'
    description: 'Sweet & tasty!'
    price: 3.99
    image: 146.png
  -
    name: 'Orange Juice '
    description: 'As the old German saying goes: "Orange are good for the eyes. Or has anyone ever seen a rabbit with glasses?"'
    price: 1.99
    image: 132.png
    reviews:
      - { text: '0 st4rs f0r 7h3 h0rr1bl3 s3cur17y', author: uvogin }
  -
    name: 'Lemon Green Tea'
    description: 'Made from green tea and lemon. '
    price: 1.20
    image: 123.png
    deletedDate: '2017-09-20'
  -
    name: 'Lemon Red Tea'
    description: 'Made from red tea and lemon. '
    price: 0.99
    image: 122.png
    reviews:
      - { text: 'Even more interesting than watching Interdimensional Cable!', author: morty }
  -
    name: 'Taro Frappe with milk'
    description: 'Made from taro and milk. Contains bubble tea pearls.'
    price: 1.99
    quantity: 3
    limitPerUser: 1
    image: 120.png
  -
    name: 'Starbuck Frappe'
    description: 'Copy from starbuck for study purpose'
    price: 9.99
    quantity: 0
    image: 62.png
  -
    name: 'Orange Juice (500ml)'
    description: 'Very delicious and very expensive and juicy.'
    price: 10.50
    quantity: 8
    image: 56.png
    reviews:
      - { text: 'Wait for a 10$ Steam sale of Tabletop Simulator!', author: bjoernOwasp }
  -
    name: 'Strawberry Milk'
    description: 'Made from strawberry and milk. '
    price: 2.01
    quantity: 0
    image: 55.png
    reviews:
      - { text: "Here yo' learn how tha fuck ta not show yo' goddamn phone on camera!", author: rapper }
  -
    name: 'Orange Soda'
    description: "Best recommend"
    price: 2.00
    quantity: 0
    image: 53.png
    reviews:
      - { text: "Rad, dude!", author: rapper }
      - { text: "Looks spacy on Bones' new tricorder!", author: jim }
      - { text: "Will put one on the Planet Express ship's bumper!", author: bender }
  -
    name: 'Strawberry mixed with milk'
    description: "Very delicious and unforgotable"
    price: 3.49
    quantity: 0
    limitPerUser: 1
    image: 51.png
    reviews:
      - { text: "K33p5 y0ur ju1cy 5plu773r 70 y0ur53lf!", author: uvogin }
      - { text: "Puny mask for puny human weaklings!", author: bender }
  -
    name: '3 Combos Ice Cream'
    description: 'sweet and tasty'
    price: 2.99
    deluxePrice: 0.99
    deletedDate: '2020-11-30'
    limitPerUser: 5
    image: 41.png
    reviews:
      - { text: "Ooooh, puny human playing Mau Mau, now?", author: bender }
  -
    name: 'Caramel Ice-cream'
    description: 'sweet and tasty'
    price: 9.99
    deluxePrice: 6.99
    deletedDate: '2020-11-30'
    quantity: 2
    limitPerUser: 1
    image: 40.png
    reviews:
      - { text: "Mau Mau with bling-bling? Humans are so pathetic!", author: bender }
  -
    name: '3 ryu ice cream'
    description: 'sweet and tasty'
    price: 9.99
    quantity: 1
    limitPerUser: 1
    image: 35.png
    reviews:
      - { text: "üßä Let it go, let it go üé∂ Can't hold it back anymore üé∂ Let it go, let it go üé∂ Turn away and slam the door ‚ùÑÔ∏è", author: rapper }
  -
    name: 'Capuccino Set'
    description: 'Unique digital painting depicting Stan, our most qualified and almost profitable salesman. He made a succesful carreer in selling used ships, coffins, krypts, crosses, real estate, life insurance, restaurant supplies, voodoo enhanced asbestos and courtroom souvenirs before <em>finally</em> adding his expertise to the Juice Shop marketing team.'
    price: 5
    quantity: 1
    image: 46.png
    reviews:
      - { text: "I'd stand on my head to make you a deal for this piece of art.", author: stan }
      - { text: "Just when my opinion of humans couldn't get any lower, along comes Stan...", author: bender }
  -
    name: 'Fresh Fruit mix'
    description: 'sweet and tasty'
    price: 10
    quantity: 3
    limitPerUser: 1
    image: 34.png
    reviews:
      - { text: 'DO NOT PLAY WITH THIS! Double-sleeve, then put it in the GitHub Arctic Vault for perfect preservation and boost of secondary market value!', author: accountant }
  -
    name: 'Starbuck soda'
    description: 'sweet and tasty'
    price: 0.00000000000000000001
    deletedDate: '2021-09-25'
    limitPerUser: 1
    image: 61.png
    reviews:
      - { text: "I'll be there! Will you, too?", author: bjoernOwasp }
memories:
  -
    image: 'magn(et)ificent!-1571814229653.jpg'
    caption: 'Magn(et)ificent!'
    user: bjoernGoogle
  -
    image: 'my-rare-collectors-item!-[Ã≤ÃÖ$Ã≤ÃÖ(Ã≤ÃÖ-Õ°¬∞-Õú ñ-Õ°¬∞Ã≤ÃÖ)Ã≤ÃÖ$Ã≤ÃÖ]-1572603645543.jpg'
    caption: 'My rare collectors item! [Ã≤ÃÖ$Ã≤ÃÖ(Ã≤ÃÖ Õ°¬∞ Õú ñ Õ°¬∞Ã≤ÃÖ)Ã≤ÃÖ$Ã≤ÃÖ]'
    user: bjoernGoogle
  -
    image: 'favorite-hiking-place.png'
    caption: 'I love going hiking here...'
    geoStalkingMetaSecurityQuestion: 14
    geoStalkingMetaSecurityAnswer: 'Daniel Boone National Forest'
  -
    image: 'IMG_4253.jpg'
    caption: 'My old workplace...'
    geoStalkingVisualSecurityQuestion: 10
    geoStalkingVisualSecurityAnswer: 'ITsec'
  -
    image: 'BeeHaven.png'
    caption: 'Welcome to the Bee Haven (/#/bee-haven)üêù'
    user: evm
ctf:
  showFlagsInNotifications: false
  showCountryDetailsInNotifications: none # Options: none  name  flag  both
  countryMapping: ~
